### ISSUE TITLE
фогстрим ревью

### ISSUE THREAD

**Issue by nikvst** [fadedDexofan/fogstream_test#1]
Все круто, есть небольшие замечания.

1. Нормализация БД.
  - Не уверен, что связь addresses <--> employees должна быть много ко многим.
  - таблица data лишняя, можно было обойтись json field в employees
  - на счет связи position <--> employee много ко многим тоже не уверен, кажется в нашей исходной схеме один рабочий может занимать только одну должность

2. settings.py
  - следует выносить часть настроек в другое место (в переменные окружения, в .ini, .yml, .json фай$
    https://hackernoon.com/4-ways-to-manage-the-configuration-in-python-4623049e841b
  - DEBUG можно было указать False перед релизом и указать возможные ALLOWED_HOST (* тоже подойдет)
  - сгенерированные самой django комментарии стоит убирать (относится ко всему проекту)

3. В тестах немного хромает pep8. Но все равно большой + за тесты.

4. email_admin/views.py
  - для проверки на авторизованность можно пользоваться миксином
    from django.contrib.auth.mixins import LoginRequiredMixin

**Comment by fadedDexofan** [comment]
@nikvst 2, 4: https://github.com/fadedDexofan/fogstream_test/commit/2b9865a303757f92e288547cd6eaa61c4a11cedb 

Таблицы: https://github.com/fadedDexofan/fogstream_test/commit/dd94f7232be1a602fecf1291cac0b6b96a140c03
По поводу связей, там на схеме как раз несколько должностей и адрессов у сотрудника. Эти должности и адреса повторяются у разных сотрудников. Поэтому M2M связь :D

**Comment by nikvst** [comment]
@fadedDexofan, да, все верно, тут я задание подзабыл
